project:
  type: website

website:
  title: "DataScapeDiaries"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ETC5523-2023/blog-aani0005
format:
  html:
    theme: lux
    css: styles.css



